batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models\03_handwriting_recognition\202306251138
train_epochs: 1000
train_workers: 20
vocab: jfBcO,A'5JmT.X/ypd"L(oGsUD2-nRIu4KZS97)v+qhWM#kl1NEx:?rH6YaVFwQ0tgCze8P&*!i3b;
width: 128
